<?php 
require_once('support/config.php');
require_once('config.connect.php');
  if(empty($_SESSION[WEBAPP]['user'])){
    redirect("index.php");
    die();
  }
?>
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>CATEGORIES</title>


<script type="text/javascript">
$(document).ready(function(){
    $(".show-text").click(function(){
      $('#myModal').find(".lots-of-text").toggle();
        $('#myModal').modal('handleUpdate');
    });
});
</script>
<style type="text/css">
.bs-example{
  margin: 20px;
}
.lots-of-text{
    display: none;
}
</style>



<style>
#panel {
    padding-top: 50px;
     padding-bottom: 50px;
    display: none;
}
button 
{
	text-decoration: none !important;
}
table td
{
	
}
</style>


<script>
$(document).ready(function(){

    $("#addbtn").click(function(){
        $("#panel").slideToggle("slow");
    });


});




</script>


</head>
<?php

?>
<body>
  
  <div class="container">



<BR><BR><BR>

            <h1>USER ADMIN</h1>
            <hr>
              <!-- ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| -->

        <button id="addbtn" type='button'  style="width:100%;" class="btn btn-info">Add</button>



        <div id="panel">

         
          <form  role="form" action="sub_useradmin.php" method="post"  id="partpost" enctype="multipart/form-data" >
          <input type='hidden' class='form-control' name='action' value='add'>
  <div class="form-group">
      <label >Part Picture:</label>

      <input type="file" name="userPic" accept="image/*" class="form-control"  required id="userPic">
    </div> 


            <div class="form-group">
              <label >Username:</label>
              <input type="text" class="form-control" id="username" name="username" required>
            </div>
             <div class="form-group">
              <label >Full Name:</label>
              <input type="text" class="form-control" id="fullname" name="fullname" required>
            </div>
             <div class="form-group">
              <label >Contact No.:</label>
              <input type="text" class="form-control" id="contact" name="contact" required>
            </div>
            


         <input type="submit" name="submit" id="submit" class="btn btn-success" value="Submit" />  

          </form>




        <!-- ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| -->
          </div>
          <br>
          <hr>
          <br>

          
          <table id="autoGeneratedID" role="grid" class="table table-striped table-bordered" style="border-collapse:collapse; table-layout:fixed;">
            <caption class="sr-only"></caption>
            <thead>
              <tr>
                <th  role="gridcell">USER ID</th>
                <th  role="gridcell">PICTURE</th>
                <th  role="gridcell">USERNAME</th>
                <th  role="gridcell">STATUS</th>

                <th>ACTION</th>
              </tr>
            </thead>


            <?php 


        $query=mysqli_query($c1,'SELECT * FROM admin_account');


        echo "<tbody>";






        while ($fetch=mysqli_fetch_assoc($query))
        	{
        	
        	echo "<tr>";
        	echo "<td style='vertical-align: middle;' ><center><p>";
        		echo $fetch['id'];
        	echo "</p></center></td>";
          echo "<td style='vertical-align: middle;' ><center><p>";
          echo "<img src='".$fetch['picture']."'' width='50' height='50'>" ;
          echo "</p></center></td>";

        	echo "<td style='vertical-align: middle;' ><center><p>";
        	echo $fetch['email'];
        	echo "</p></center></td>";

          echo "<td style='vertical-align: middle;' ><center><p>";
          if ($fetch['is_deactivate']==0):
            echo "Active";
          else:
           echo "Deactivated";
         endif;
          echo "</p></center></td>";
        	


        	echo "<td style='vertical-align: middle;' >";
          
          $Mymodal="Mymodal".$fetch['id'];
        $Yourmodal="Yourmodal".$fetch['id'];
        $Yourmodal2="Yourmodal2".$fetch['id'];
        		echo '<center>';

          if ($fetch['is_deactivate']==0):
            echo ' <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#'.$Mymodal.'" ><i class="glyphicon glyphicon-edit"></i></button>
             <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#'.$Yourmodal.'"><i class="glyphicon glyphicon-remove"></i></button></center>';


          else:
           echo '<button type="button" class="btn btn-info" data-toggle="modal" data-target="#'.$Yourmodal2.'"><i class="fa fa-check" aria-hidden="true"></i></button></center>';

         endif;

            



        	echo "</td>";

        	echo "</tr>";


           
        echo
        "
            
            <!-- Modal HTML -->
            <div id='".$Mymodal."' class='modal fade'>
                <div class='modal-dialog'>
                    <div class='modal-content'>
                        <div class='modal-header'>
                            <button type='button' class='close' data-dismiss='modal' aria-hidden='true'>&times;</button>
                            <h4 class='modal-title'>EDIT FORM </h4>
                        </div>
                        <div class='modal-body'>
                         
         <form  role='form' action='sub_useradmin.php' method='post' enctype='multipart/form-data' >
            <div class='form-group'>
              
              <input type='hidden' class='form-control' name='action' value='edit'>
              <input type='hidden' class='form-control' id='editcategoryId' name='id' value='".$fetch['id']."'>
              <label >Username:</label>
              <input type='text' class='form-control' id='editcategoryName' name='username' value='".$fetch['email']."' >
              <label >Full Name:</label>
              <input type='text' class='form-control' id='fullname' name='fullname' value='".$fetch['full_name']."' required>
              <label >Contact:</label>
              <input type='text' class='form-control' id='contact' name='contact' value='".$fetch['contact_no']."' required>
            </div>
         

         



                        </div>
                        <div class='modal-footer'>
                            <button type='submit' name='edit' id='submit' class='btn btn-success'>Save</button>
                            <button type='button' class='btn btn-danger' data-dismiss='modal'>Close</button>
          </form>
                        </div>
                    </div>
                </div>
            </div>
        ";


        //==========================================================================
        echo
        "
            
            <!-- Modal HTML -->
            <div id='".$Yourmodal."' class='modal fade'>
                <div class='modal-dialog'>
                    <div class='modal-content'>
                        <div class='modal-header'>
                            <button type='button' class='close' data-dismiss='modal' aria-hidden='true'>&times;</button>
                            <h4 class='modal-title'>EDIT FORM </h4>
                        </div>
                        <div class='modal-body'>
                         
         <form  role='form' action='sub_useradmin.php' method='post' enctype='multipart/form-data' >
            <div class='form-group'>
            <input type='hidden' class='form-control' name='action' value='delete'>
              <input type='hidden' class='form-control' name='id'  value='".$fetch['id']."'>
              <label ><center>Are you sure you want to deactvate '".$fetch['email']."' ?</center></label>
              
            </div>
                        </div>
                        <div class='modal-footer'>
                            <button type='submit' name='delete' class='btn btn-success'>Yes</button>
                            <button type='button' class='btn btn-danger' data-dismiss='modal'>No</button>
          </form>
                        </div>
                    </div>
                </div>
            </div>
        ";

        echo
        "
            
            <!-- Modal HTML -->
            <div id='".$Yourmodal2."' class='modal fade'>
                <div class='modal-dialog'>
                    <div class='modal-content'>
                        <div class='modal-header'>
                            <button type='button' class='close' data-dismiss='modal' aria-hidden='true'>&times;</button>
                            <h4 class='modal-title'>EDIT FORM </h4>
                        </div>
                        <div class='modal-body'>
                         
         <form  role='form' action='sub_useradmin.php' method='post' enctype='multipart/form-data' >
            <div class='form-group'>
            <input type='hidden' class='form-control' name='action' value='activate'>
              <input type='hidden' class='form-control' name='id'  value='".$fetch['id']."'>
              <label ><center>Are you sure you want to actvate '".$fetch['email']."' ?</center></label>
              
            </div>
                        </div>
                        <div class='modal-footer'>
                            <button type='submit' name='delete' class='btn btn-success'>Yes</button>
                            <button type='button' class='btn btn-danger' data-dismiss='modal'>No</button>
          </form>
                        </div>
                    </div>
                </div>
            </div>
        ";
        	} 
         echo "</tbody>";        



        ?>








          </table>
        <!-- Button trigger modal -->
        <div class="bs-example">
            <div class="alert alert-info fade in">
                <a href="#" class="close" data-dismiss="alert">&times;</a>
                <strong>Note!</strong>  bakit ka tinatamad wag ka tamarin loko ka para to sa kinabukasan mo
            </div>
            
            <!-- Button HTML (to Trigger Modal) -->
          
        </div>

</body>
<script src='http://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js'></script>
<script src='http://cdn.datatables.net/1.10.10/js/dataTables.bootstrap.min.js'></script>




<script src="DatatableR/js/js.datatablecat.js"></script>



</html>


