<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>PRODUCTS</title>

<script type="text/javascript">
$(document).ready(function(){
    $(".show-text").click(function(){
      $('#myModal').find(".lots-of-text").toggle();
        $('#myModal').modal('handleUpdate');
    });
});
</script>
<style type="text/css">
.bs-example{
  margin: 20px;
}
.lots-of-text{
    display: none;
}
</style>





<style>
#panel {
    padding-top: 50px;
     padding-bottom: 50px;
    display: none;
}
button 
{
	text-decoration: none !important;
}
table td
{
	
}
</style>


<script>
$(document).ready(function(){

    $("#addbtn").click(function(){
        $("#panel").slideToggle("slow");
    });


});




</script>


</head>
<?php
require_once('config.connect.php');
?>
<body>
  <div class="container">


<br><br><br>


    <h1>USERS</h1>
    <hr>
      <!-- ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| -->




<div id="panel">

 






 <input type="submit" name="submit" id="submit" class="btn btn-success" value="Submit" />  

  </form>




<!-- ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| -->
  </div>
  
  <br>

  
  <table id="autoGeneratedID" role="grid" class="table table-striped table-bordered" style="border-collapse:collapse; table-layout:fixed;">
    <caption class="sr-only"></caption>
    <thead>
      <tr>
        <th  role="gridcell">USER ID</th>
        <th  role="gridcell">EMAIL</th>
        <th  role="gridcell">FULL NAME</th>
        <th  role="gridcell">STATUS</th>
        <th  >ACTION</th>
      </tr>
    </thead>


    <?php 


$query=mysqli_query($c1,'SELECT * FROM user');


echo "<tbody>";






while ($fetch=mysqli_fetch_assoc($query))
	{
	
	echo "<tr>";
	echo "<td style='vertical-align: middle;' ><center><p>";
		echo $fetch['id'];  
	echo "</p></center></td>";

	echo "<td style='vertical-align: middle;' ><center><p>";
		echo $fetch['email'];
	echo "</p></center></td>";
  echo "<td style='vertical-align: middle;' ><center><p>";
    echo $fetch['full_name'];
  echo "</p></center></td>";
echo "<td style='vertical-align: middle;' ><center><p>";
          if ($fetch['is_deactivate']==0):
            echo "Active";
          else:
           echo "Deactivated";
         endif;
          echo "</p></center></td>";

 



	echo "<td style='vertical-align: middle;' >";
  
  $Mymodal="Mymodal".$fetch['id'];
$Yourmodal="Yourmodal".$fetch['id'];
$Yourmodal2="Yourmodal2".$fetch['id'];
		echo '<center>';

 if ($fetch['is_deactivate']==0):
            echo '<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#'.$Yourmodal.'"><i class="glyphicon glyphicon-remove"></i></button></center>';


          else:
           echo '<button type="button" class="btn btn-info" data-toggle="modal" data-target="#'.$Yourmodal2.'"><i class="fa fa-check" aria-hidden="true"></i></button></center>';

         endif;

     


	echo "</td>";

	echo "</tr>";


   

    
   


//==========================================================================
echo
"
    
    <!-- Modal HTML -->
    <div id='".$Yourmodal."' class='modal fade'>
        <div class='modal-dialog'>
            <div class='modal-content'>
                <div class='modal-header'>
                    <button type='button' class='close' data-dismiss='modal' aria-hidden='true'>&times;</button>
                    <h4 class='modal-title'>EDIT FORM </h4>
                </div>
                <div class='modal-body'>
                 
 <form  role='form' action='sub_user.php' method='post' enctype='multipart/form-data'>
    <div class='form-group'>
       <input type='hidden' class='form-control' name='action'  value='delete'>
      <input type='hidden' class='form-control' id='delassignId' name='id'  value='".$fetch['id']."'>

      <label ><center>Are you sure you want to deactivate '".$fetch['email']."' ?</center></label>
      
    </div>
                </div>
                <div class='modal-footer'>
                    <button type='submit' name='submit' id='submit' class='btn btn-success'>Yes</button>
                    <button type='button' class='btn btn-danger' data-dismiss='modal'>No</button>
  </form>
                </div>
            </div>
        </div>
    </div>
";
echo
"
    
    <!-- Modal HTML -->
    <div id='".$Yourmodal2."' class='modal fade'>
        <div class='modal-dialog'>
            <div class='modal-content'>
                <div class='modal-header'>
                    <button type='button' class='close' data-dismiss='modal' aria-hidden='true'>&times;</button>
                    <h4 class='modal-title'>EDIT FORM </h4>
                </div>
                <div class='modal-body'>
                 
 <form  role='form' action='sub_user.php' method='post' enctype='multipart/form-data'>
    <div class='form-group'>
       <input type='hidden' class='form-control' name='action'  value='activate'>
      <input type='hidden' class='form-control' name='id'  value='".$fetch['id']."'>

      <label ><center>Are you sure you want to activate '".$fetch['email']."' ?</center></label>
      
    </div>
                </div>
                <div class='modal-footer'>
                    <button type='submit' name='submit' id='submit' class='btn btn-success'>Yes</button>
                    <button type='button' class='btn btn-danger' data-dismiss='modal'>No</button>
  </form>
                </div>
            </div>
        </div>
    </div>
";
	} 
 echo "</tbody>";        



?>








  </table>
<!-- Button trigger modal -->
<div class="bs-example">
    <div class="alert alert-info fade in">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <strong>Note!</strong>  bakit ka tinatamad wag ka tamarin loko ka para to sa kinabukasan mo
    </div>
    
    <!-- Button HTML (to Trigger Modal) -->
  
</div>


<script src='http://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js'></script>
<script src='http://cdn.datatables.net/1.10.10/js/dataTables.bootstrap.min.js'></script>




    <script src="DatatableR/js/js.datatableass.js"></script>

<script type="text/javascript">
// Javascript

 
</script>
</body>
</html>


