<?php 
require_once('support/config.php');
require_once('config.connect.php');
  if(empty($_SESSION[WEBAPP]['user'])){
    redirect("index.php");
    die();
  }
?>
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>CATEGORIES</title>
  
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    $(".show-text").click(function(){
      $('#myModal').find(".lots-of-text").toggle();
        $('#myModal').modal('handleUpdate');
    });
});
</script>
<style type="text/css">
.bs-example{
  margin: 20px;
}
.lots-of-text{
    display: none;
}
</style>




  
  <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>
<link rel='stylesheet prefetch' href='http://cdn.datatables.net/1.10.10/css/dataTables.bootstrap.min.css'>

<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

      <link rel="stylesheet" href="DatatableR/css/css.datatables.css">
<style>
#panel {
    padding-top: 50px;
     padding-bottom: 50px;
    display: none;
}
button 
{
	text-decoration: none !important;
}
table td
{
	
}
</style>


<script>
$(document).ready(function(){

    $("#addbtn").click(function(){
        $("#panel").slideToggle("slow");
    });


});




</script>


</head>

<body>
  
  <div class="container">



<BR><BR><BR>

            <h1>CATEGORIES</h1>
            <hr>
              <!-- ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| -->

        <button id="addbtn" type='button'  style="width:100%;" class="btn btn-info">Add</button>



        <div id="panel">

         
          <form  role="form" action="sub_category.php" method="post" id="categorypost" enctype="multicategory/form-data">
            <div class="form-group">
              <label >Category Name:</label>
              <input type="text" class="form-control" id="categoryName" name="categoryName" required>
            </div>



         <input type="submit" name="submit" id="submit" class="btn btn-success" value="Submit" />  

          </form>




        <!-- ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| -->
          </div>
          <br>
          <hr>
          <br>

          
          <table id="autoGeneratedID" role="grid" class="table table-striped table-bordered" style="border-collapse:collapse; table-layout:fixed;">
            <caption class="sr-only"></caption>
            <thead>
              <tr>
                <th  role="gridcell">CATEGORY ID</th>
                <th  role="gridcell">CATEGORY NAME</th>

                <th>CATEGORY ACTION</th>
              </tr>
            </thead>


            <?php 


        $query=mysqli_query($c1,'SELECT * FROM category');


        echo "<tbody>";






        while ($fetch=mysqli_fetch_assoc($query))
        	{
        	
        	echo "<tr>";
        	echo "<td style='vertical-align: middle;' ><center><p>";
        		echo $fetch['category_id'];
        	echo "</p></center></td>";

        	echo "<td style='vertical-align: middle;' ><center><p>";
        		echo $fetch['category_name'];
        	echo "</p></center></td>";

        	


        	echo "<td style='vertical-align: middle;' >";
          
          $Mymodal="Mymodal".$fetch['category_id'];
        $Yourmodal="Yourmodal".$fetch['category_id'];
        		echo '<center>



             <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#'.$Mymodal.'" ><i class="glyphicon glyphicon-edit"></i></button>
             <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#'.$Yourmodal.'"><i class="glyphicon glyphicon-remove"></i></button></center>';




        	echo "</td>";

        	echo "</tr>";


           
        echo
        "
            
            <!-- Modal HTML -->
            <div id='".$Mymodal."' class='modal fade'>
                <div class='modal-dialog'>
                    <div class='modal-content'>
                        <div class='modal-header'>
                            <button type='button' class='close' data-dismiss='modal' aria-hidden='true'>&times;</button>
                            <h4 class='modal-title'>EDIT FORM </h4>
                        </div>
                        <div class='modal-body'>
                         
         <form  role='form' action='edit_category.php' method='post' id='categoryeditpost' enctype='multicategory/form-data'>
            <div class='form-group'>
              <input type='text' class='form-control' id='editcategoryId' name='editcategoryId'  style='opacity:0;' value='".$fetch['category_id']."'>
              <label >Category Name:</label>
              <input type='text' class='form-control' id='editcategoryName' name='editcategoryName' placeholder='".$fetch['category_name']."' >
            </div>
         

         



                        </div>
                        <div class='modal-footer'>
                            <button type='submit' name='submit' id='submit' class='btn btn-success'>Save</button>
                            <button type='button' class='btn btn-danger' data-dismiss='modal'>Close</button>
          </form>
                        </div>
                    </div>
                </div>
            </div>
        ";


        //==========================================================================
        echo
        "
            
            <!-- Modal HTML -->
            <div id='".$Yourmodal."' class='modal fade'>
                <div class='modal-dialog'>
                    <div class='modal-content'>
                        <div class='modal-header'>
                            <button type='button' class='close' data-dismiss='modal' aria-hidden='true'>&times;</button>
                            <h4 class='modal-title'>EDIT FORM </h4>
                        </div>
                        <div class='modal-body'>
                         
         <form  role='form' action='del_category.php' method='post' id='categorydelpost' enctype='multicategory/form-data'>
            <div class='form-group'>
              <input type='text' class='form-control' id='delcategoryId' name='delcategoryId'  style='opacity:0;' value='".$fetch['category_id']."'>
              <label ><center>Are you sure you want to delete '".$fetch['category_name']."' ?</center></label>
              
            </div>
                        </div>
                        <div class='modal-footer'>
                            <button type='submit' name='submit' id='submit' class='btn btn-success'>Yes</button>
                            <button type='button' class='btn btn-danger' data-dismiss='modal'>No</button>
          </form>
                        </div>
                    </div>
                </div>
            </div>
        ";
        	} 
         echo "</tbody>";        



        ?>








          </table>
        <!-- Button trigger modal -->
        <div class="bs-example">
            <div class="alert alert-info fade in">
                <a href="#" class="close" data-dismiss="alert">&times;</a>
                <strong>Note!</strong>  bakit ka tinatamad wag ka tamarin loko ka para to sa kinabukasan mo
            </div>
            
            <!-- Button HTML (to Trigger Modal) -->
          
        </div>

</body>
<script src='http://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js'></script>
<script src='http://cdn.datatables.net/1.10.10/js/dataTables.bootstrap.min.js'></script>




<script src="DatatableR/js/js.datatablecat.js"></script>



</html>


