<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>PRODUCTS</title>
  


  
  <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>
<link rel='stylesheet prefetch' href='http://cdn.datatables.net/1.10.10/css/dataTables.bootstrap.min.css'>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

      <link rel="stylesheet" href="DatatableR/css/css.datatables.css">
<style>
#panel {
    padding-top: 50px;
     padding-bottom: 50px;
    display: none;
}
button 
{
	text-decoration: none !important;
}
table td
{
	
}
</style>


<script>
$(document).ready(function(){

    $("#addbtn").click(function(){
        $("#panel").slideToggle("slow");
    });


	





});




</script>


</head>
<?php
require_once('config.connect.php');
?>
<body>
  <div class="container">





    <h1>PRODUCTS</h1>
    <hr>
      <!-- ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| -->

<button id="addbtn" type='button'  style="width:100%;" class="btn btn-info">Add</button>



<div id="panel">

 
  <form  role="form" action="sub_brand.php" method="post" id="create-cor" enctype="multipart/form-data">
    <div class="form-group">
      <label >Brand Name:</label>
      <input type="text" class="form-control" id="BrandName" name="BrandName" required>
    </div>
  <div class="form-group">
      <label >Brand Picture:</label>
      <input type="file" name="BrandPic" accept="image/*" class="form-control"  required id="BrandPic">
    </div> 
     <div class="form-group">
      <label >Brand Description:</label>
      <input type="textarea" class="form-control" name="BrandDesc" id="BrandDesc" required>
    </div>


 <input type="submit" name="submit" id="submit" class="btn btn-success" value="Submit" />  

  </form>




<!-- ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||| -->
  </div>
  <br>
  <hr>
  <br>

  
  <table id="autoGeneratedID" role="grid" class="table table-striped table-bordered" style="border-collapse:collapse; table-layout:fixed;">
    <caption class="sr-only"></caption>
    <thead>
      <tr>
        <th  role="gridcell">BRAND ID</th>
        <th  role="gridcell">BRAND NAME</th>
        <th  role="gridcell">BRAND PICTURE</th>
        <th  role="gridcell">BRAND DESCRIPTION</th>
        <th  ">BRAND ACTION</th>
      </tr>
    </thead>


    <?php 


$query=mysqli_query($c1,'SELECT * FROM brand');


echo "<tbody>";

while ($fetch=mysqli_fetch_assoc($query))
	{
	
	echo "<tr>";
	echo "<td style='vertical-align: middle;' ><center><p>";
		echo $fetch['brand_id'];
	echo "</p></center></td>";

	echo "<td style='vertical-align: middle;' ><center><p>";
		echo $fetch['brand_name'];
	echo "</p></center></td>";

	echo "<td style='vertical-align: middle;' ><center><p>";
		echo "<img src='".$fetch['brand_pic']."'' width='50' height='50'>" ;
	echo "</p></center></td>";

	echo "<td style='vertical-align: middle;' ><center><p>";	

    $exceed=strlen($fetch['brand_desc']);
if($exceed > 20)
{
  echo substr(($fetch['brand_desc']),0,17) . " ...";

}
 else
  {
    echo  $fetch['brand_desc'];
  }

	echo "</p></center></td>";

	echo "<td style='vertical-align: middle;' >";
		echo "<center><button type='button' class='btn btn-warning'><i class='glyphicon glyphicon-edit'></i></button> <button type='button' class='btn btn-danger'><i class='glyphicon glyphicon-remove'></i></button></center>";
	echo "</td>";

	echo "</tr>";
	} 
 echo "</tbody>";        



?>




  </table>

</div>

  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src='http://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js'></script>
<script src='http://cdn.datatables.net/1.10.10/js/dataTables.bootstrap.min.js'></script>

    <script src="DatatableR/js/js.datatable.js"></script>

</body>
</html>


